name: Deploy to Snowflake

on:
  workflow_call:
    inputs:
      my_env:
        required: true
        type: string

jobs:
  deploy-snowflake:
    runs-on: ubuntu-latest
    environment: ${{ inputs.my_env }}
    env:
      SF_ACCOUNT: ${{ vars.SF_ACCOUNT }}
      SF_USERNAME: ${{ vars.SF_USER }}
      SF_ROLE: ${{ vars.SF_ROLE }}
      SF_WAREHOUSE: ${{ vars.SF_WAREHOUSE }}
      SF_DATABASE: ${{ vars.SF_DATABASE }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download SnowSQL
        run:  curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash
      
      - name: Install SnowSQL
        run: SNOWSQL_DEST=~/snowflake SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash
      
      - name: Test installation
        run:  ~/snowflake/snowsql -v

      - name: Deploy SQL to Snowflake
        run: |
          ~/snowflake/snowsql -a $SF_ACCOUNT \
                    -u $SF_USERNAME \
                    -p $SNOWFLAKE_PASSWORD \
                    -r $SF_ROLE \
                    -f structure/database.sql