name: Deploy to Snowflake

on:
  workflow_call:
    inputs:
      my_env:
        required: true
        type: string

jobs:
  deploy-snowflake:
    runs-on: ubuntu-latest
    environment: ${{ inputs.my_env }}
    env:
      SNOWSQL_ACCOUNT: ${{ vars.SF_ACCOUNT }}
      SNOWSQL_USER: ${{ vars.SF_USER }}
      #SNOWSQL_ROLE: ${{ vars.SF_ROLE }}
      #SF_WAREHOUSE: ${{ vars.SF_WAREHOUSE }}
      #SF_DATABASE: ${{ vars.SF_DATABASE }}
      SNOWSQL_PWD: ${{ secrets.SF_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python and dependencies
        run: pip install jinja2 pyyaml

      - name: Create output folder
        run: mkdir -p rendered

      - name: Render SQL template
        run: python render.py ${{ inputs.my_env || 'dev' }}

      - name: Download SnowSQL
        run:  curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.3/linux_x86_64/snowsql-1.3.3-linux_x86_64.bash
      
      - name: Install SnowSQL
        run: SNOWSQL_DEST=~/snowflake SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.3.3-linux_x86_64.bash
      
      - name: Test installation
        run:  ~/snowflake/snowsql -v

      - name: Deploy SQL to Snowflake
        run: ~/snowflake/snowsql -f rendered/BEGA_HR_DATA_${{ inputs.my_env || 'dev' }}.sql