name: snowflake-devops-demo

# Controls when the action will run. 
on:
  push:
    branches:
      - main
    paths:
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-dev:
    uses: ./.github/workflows/deploy-snowflake.yml
    with:
      my_env: dev 
    secrets: inherit
  deploy-prod:
    needs: deploy-dev
    uses: ./.github/workflows/deploy-snowflake.yml
    with:
      my_env: prod 
    secrets: inherit