name: snowflake-devops-demo

# Controls when the action will run. 
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - uat
          - prod

jobs:
  deploy-bega:
    uses: ./.github/workflows/deploy-snowflake.yml
    with:
      my_env: ${{ github.event.inputs.environment }} 
    secrets: inherit