name: snowflake-devops-demo

# Controls when the action will run. 
on:
  push:
    branches:
      - main
    paths:
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    env:
      SF_ACCOUNT: ${{ vars.SF_ACCOUNT }}
      SF_USERNAME: ${{ vars.SF_USER }}
      SF_ROLE: ${{ vars.SF_ROLE }}
      SF_WAREHOUSE: ${{ vars.SF_WAREHOUSE }}
      SF_DATABASE: ${{ vars.SF_DATABASE }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
    steps:
      - name: "Print SF_DATABASE"
        run: echo "SF_DATABASE=$SF_DATABASE"
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x

      - name: Run schemachange
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step 1: Installing schemachange"
          pip install schemachange
          
          echo "Step 2: Running schemachange"
          schemachange -f $GITHUB_WORKSPACE/migrations -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table
  deploy-prod:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: prod
    env:
      SF_ACCOUNT: ${{ vars.SF_ACCOUNT }}
      SF_USERNAME: ${{ vars.SF_USER }}
      SF_ROLE: ${{ vars.SF_ROLE }}
      SF_WAREHOUSE: ${{ vars.SF_WAREHOUSE }}
      SF_DATABASE: ${{ vars.SF_DATABASE }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
    steps:
      - name: "Print SF_DATABASE"
        run: echo "SF_DATABASE=$SF_DATABASE"
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x

      - name: Run schemachange
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step 1: Installing schemachange"
          pip install schemachange
          
          echo "Step 2: Running schemachange"
          schemachange -f $GITHUB_WORKSPACE/migrations -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table