name: snowflake-devops-demo

# Controls when the action will run. 
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - uat
          - prod
          - bega

jobs:
  # deploy-dev:
  #   uses: ./.github/workflows/deploy-snowflake.yml
  #   with:
  #     my_env: dev 
  #   secrets: inherit
  # deploy-prod:
  #   needs: deploy-dev
  #   uses: ./.github/workflows/deploy-snowflake.yml
  #   with:
  #     my_env: prod 
  #   secrets: inherit
  deploy-bega:
    uses: ./.github/workflows/deploy-snowflake.yml
    with:
      my_env: ${{ github.event.inputs.environment }} 
    secrets: inherit